name: CI Build

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  build:
    name: "Build Gradle Build Tool"
    runs-on: ubuntu-20.04
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - id: setup-matrix
        run: echo "::set-output name=matrix::$(cat .github/workflows/stage0.json)"
      - name: debug
        run: echo ${{ steps.setup-matrix.outputs.matrix }}
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: compileAll --no-configuration-cache
      - name: "Comment build scan url"
        uses: actions/github-script@v3
        if: github.event_name == 'pull_request' && failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ ${{ github.workflow }} failed: ${{ steps.gradle.outputs.build-scan-url }}'
            })
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    env:
      # Set the GRADLE_ENTERPRISE_ACCESS_KEY so that Gradle Build Scans are generated
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  sanity-check:
    name: "Sanity Check on Linux"
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: ./gradlew sanityCheck
        uses: gradle/gradle-build-action@v2
        with:
          arguments: sanityCheck --no-configuration-cache
      - name: "Comment build scan url"
        uses: actions/github-script@v3
        if: github.event_name == 'pull_request' && failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ ${{ github.workflow }} failed: ${{ steps.gradle.outputs.build-scan-url }}'
            })
    env:
      # Set the GRADLE_ENTERPRISE_ACCESS_KEY so that Gradle Build Scans are generated
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  parallel-test:
    name: "Test Gradle on Linux"
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      matrix:
        subprojects: ${{ fromJson(needs.build.outputs.matrix).*.subprojects }}
      fail-fast: false
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: ./gradlew ${{ join(matrix.subprojects, ':quickTest ') }}
        id: gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ join(matrix.subprojects, ':quickTest ') }}:quickTest --no-configuration-cache
      - name: "Comment build scan url"
        uses: actions/github-script@v3
        if: github.event_name == 'pull_request' && failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ ${{ github.workflow }} failed: ${{ steps.gradle.outputs.build-scan-url }}'
            })
    env:
      # Set the GRADLE_ENTERPRISE_ACCESS_KEY so that Gradle Build Scans are generated
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
