name: CI Build

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  build:
    name: "Build Gradle Build Tool Contributor Build"
    runs-on: ubuntu-20.04
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - id: setup-matrix
        run: echo "::set-output name=matrix::$(jq -c . .github/workflows/stage1.json)"
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: write test-split
        run: |
          cat <<EOF
            ${{ toJson(fromJson(steps.setup-matrix.outputs.matrix)[0].classes) }}
          EOF
          | jq -r ". | .[]" > test-splits.properties
      - name: debug-properties
        run: cat test-splits.properties
