name: Contributor CI Build

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  build:
    name: "Build Gradle Build Tool Contributor Build"
    runs-on: ubuntu-20.04
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - id: setup-matrix
        run: echo "::set-output name=matrix::$(jq -c -f .github/workflows/extract-matrix.jq .github/workflows/stage1.json)"
      - id: debug
        run: echo "${{ steps.setup-matrix.outputs.matrix }}"
#      - name: setup java
#        uses: actions/setup-java@v2
#        with:
#          distribution: temurin
#          java-version: 11
#      - name: assemble
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: compileAll --no-configuration-cache
#      - name: "Comment build scan url"
#        uses: actions/github-script@v3
#        if: github.event_name == 'pull_request' && failure()
#        with:
#          github-token: ${{secrets.GITHUB_TOKEN}}
#          script: |
#            github.issues.createComment({
#              issue_number: context.issue.number,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              body: '❌ ${{ github.workflow }} failed: ${{ steps.gradle.outputs.build-scan-url }}'
#            })
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    env:
      # Set the GRADLE_ENTERPRISE_ACCESS_KEY so that Gradle Build Scans are generated
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  linux-parallel-test:
    name: "${{ matrix.bucket.name }}"
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      matrix:
        bucket: ${{ fromJson(needs.build.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: remove test splits
        run: |
          rm -rf test-splits
          mkdir test-splits
      - name: write test-split
        if: ${{ matrix.bucket.filter }}
        run: |
          echo 'jq -r ".[${{ matrix.bucket.index }}].classes | .[]" .github/workflows/stage1.json > test-splits/${{ matrix.bucket.filename }}.properties
      - name: ./gradlew quickTest
        if: ${{ matrix.bucket.classes != null }}
        id: gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.bucket.tasks }} --no-configuration-cache
      - name: "Comment build scan url"
        uses: actions/github-script@v3
        if: github.event_name == 'pull_request' && failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ ${{ github.workflow }} failed: ${{ steps.gradle.outputs.build-scan-url }}'
            })
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: subprojects/**/build/**/test-results/**/*.xml
    env:
      # Set the GRADLE_ENTERPRISE_ACCESS_KEY so that Gradle Build Scans are generated
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      GRADLE_ENTERPRISE_TEST_DISTRIBUTION_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_TEST_DISTRIBUTION_ACCESS_KEY }}
